"""Stage-15 rank, effective-ownership and competition-utility package."""

from dmf_pulse.rank_strategy.effective_ownership import calculate_effective_ownership
from dmf_pulse.rank_strategy.manager_multipliers import (
    calculate_manager_multipliers,
    raw_projection_hash,
    shared_scenario_set_hash,
)
from dmf_pulse.rank_strategy.mini_league import simulate_mini_league_rank
from dmf_pulse.rank_strategy.models import (
    CohortKind,
    CohortMember,
    CohortSample,
    EffectiveOwnershipReport,
    ManagerChip,
    ManagerMultiplierPolicy,
    ManagerMultiplierSet,
    ManagerScenarioStanding,
    ManagerTeamPlan,
    MiniLeagueScenarioOutcome,
    PlayerOwnership,
    RankDistribution,
    RankMass,
    RankTiePolicy,
    SampleRightsStatus,
    ScenarioManagerMultiplier,
)
from dmf_pulse.rank_strategy.opponent_actions import (
    combine_opponent_action_distributions,
    model_opponent_actions,
)
from dmf_pulse.rank_strategy.opponent_models import (
    JointOpponentActionDistribution,
    JointOpponentActionScenario,
    OpponentActionCandidate,
    OpponentActionDistribution,
    OpponentActionFeatures,
    OpponentActionProbability,
    OpponentBehaviourProfile,
    OpponentChipAction,
    OpponentObservedState,
)
from dmf_pulse.rank_strategy.synthetic_field import simulate_synthetic_overall_rank
from dmf_pulse.rank_strategy.synthetic_models import (
    SyntheticApproximationStatus,
    SyntheticBandScenarioCount,
    SyntheticBandSelectionBasis,
    SyntheticManagerRepresentative,
    SyntheticOverallDistribution,
    SyntheticOverallPopulation,
    SyntheticOverallRankResult,
    SyntheticOverallScenarioOutcome,
    SyntheticPopulationDiagnostics,
    SyntheticRankBand,
)

__all__ = [
    "CohortKind",
    "CohortMember",
    "CohortSample",
    "EffectiveOwnershipReport",
    "JointOpponentActionDistribution",
    "JointOpponentActionScenario",
    "ManagerChip",
    "ManagerMultiplierPolicy",
    "ManagerMultiplierSet",
    "ManagerScenarioStanding",
    "ManagerTeamPlan",
    "MiniLeagueScenarioOutcome",
    "OpponentActionCandidate",
    "OpponentActionDistribution",
    "OpponentActionFeatures",
    "OpponentActionProbability",
    "OpponentBehaviourProfile",
    "OpponentChipAction",
    "OpponentObservedState",
    "PlayerOwnership",
    "RankDistribution",
    "RankMass",
    "RankTiePolicy",
    "SampleRightsStatus",
    "ScenarioManagerMultiplier",
    "SyntheticApproximationStatus",
    "SyntheticBandScenarioCount",
    "SyntheticBandSelectionBasis",
    "SyntheticManagerRepresentative",
    "SyntheticOverallDistribution",
    "SyntheticOverallPopulation",
    "SyntheticOverallRankResult",
    "SyntheticOverallScenarioOutcome",
    "SyntheticPopulationDiagnostics",
    "SyntheticRankBand",
    "calculate_effective_ownership",
    "calculate_manager_multipliers",
    "combine_opponent_action_distributions",
    "model_opponent_actions",
    "raw_projection_hash",
    "shared_scenario_set_hash",
    "simulate_mini_league_rank",
    "simulate_synthetic_overall_rank",
]
